pipeline {
    agent any

    environment {
        PROJECT_ROOT = 'messaging-app'
        IMAGE_NAME= 'enos137/messaging-app:latest'
    }

    stages {
        stage('Checkout code') {
            steps {
                echo 'Checking out code from GitHub...'
                git branch: 'main',
                    url: 'https://github.com/Vallor23/alx-backend-python.git',
                    credentialsId: 'github-ssh-key'
            }
        }
        stage('Install dependencies') {
            agent {
                docker {
                    image 'python:3.10'
                }
            }
            steps {
                echo 'Installing Python dependencies for messaging-app...'
                dir ("${PROJECT_ROOT}") {
                    sh '''
                        python -m venv venv
                        . venv/bin/activate
                        pip install --upgrade pip
                        pip install -r requirements.txt
                    '''
                }
            }
        }
        stage('Build Docker image') {
            steps {
                script {
                    docker build ("${IMAGE_NAME}")
                }
            }
        }
        stage('Push to Docker Hub') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'dockerhub-creds') {
                        docker.image("${IMAGE_NAME}").push()
                    }
                }
            }
        }
        stage('Run Tests') {
            agent {
                docker {
                    image 'python:3.10'
                }
            }
            steps {
                echo 'Running tests with pytest...'
                dir("${PROJECT_ROOT}") {
                    sh '''
                        . venv/bin/activate
                        mkdir -p reports
                        pytest --junitxml=reports/test-results.xml
                    '''
                }
            }
        }
        stage('Publish Test Report') {
            steps {
                junit 'reports/test-results.xml'
            }
        }
    }
    
    post {
        always {
            archiveArtifacts artifacts: 'reports/test-results.xml', allowEmptyArchive: true
        }
    }
}