pipeline {
    agent any

    environment {
        VENV_DIR= 'venv'
    }

    stages {
        stage('Checkout code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Vallor23/alx-backend-python/tree/main/messaging_app',
                    credentialsId: 'github-ssh-key'
            }
        }
        stage('Install dependencies') {
            steps {
                withPythonEnv("$VENV_DIR") {
                    sh 'pip3 install -r messaging_app/requirements.txt'
                }
            }
        }
        stage('Run Tests') {
            steps {
                withPythonEnv("$VENV_DIR") {
                    sh 'pytest --junitxml=reports/test-results.xml'
                }
            }
        }
        stage('Publish Test Report') {
            steps {
                junit 'reports/test-results.xml'
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'reports/test-results.xml', allowEmptyArchive: True
        }
    }
}