apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-green
spec:
  selector:
    matchLabels:
      app: django
      version: green
  template:
    metadata:
      labels:
        app: django
        version: green
    spec:
      containers:
      - name: django
        image: enos137/messaging-app:green
        resources:
          requests:
              memory: "128Mi"
              cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000